/* global __dirname */
// Expo's flat config bundles the react, react-hooks, import and typescript
// rule sets. Everything below either switches off a rule that does not apply
// to this project or narrows one that would otherwise be pure noise.
const expo = require("eslint-config-expo/flat");

module.exports = [
  ...expo,
  {
    // android/ is generated by prebuild. The rest is build tooling that runs
    // in Node, not in the app bundle.
    ignores: ["android/**", "coverage/**", "dist/**", "scripts/**", "plugins/**"],
  },
  {
    rules: {
      // React Compiler diagnostics. babel.config.js does not enable the
      // compiler (no `experiments.reactCompiler` in app.json either), so these
      // report on a transform that never runs. Turn them back on in the same
      // commit that enables the compiler.
      "react-hooks/refs": "off",
      "react-hooks/set-state-in-effect": "off",
      "react-hooks/immutability": "off",
      "react-hooks/preserve-manual-memoization": "off",
      "react-hooks/purity": "off",

      // Guards against `'` breaking HTML parsing. React Native renders <Text>,
      // not HTML, so an apostrophe is just an apostrophe.
      "react/no-unescaped-entities": "off",

      "import/first": "off",

      // A cycle can leave an import undefined while modules are still loading,
      // which tsc cannot see.
      "import/no-cycle": "warn",

      // Hermes has no ES2023 copying array methods, so these throw
      // "undefined is not a function" at runtime while tsc and jest pass.
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression > MemberExpression.callee > Identifier.property[name=/^(toSorted|toReversed|toSpliced)$/]",
          message: "Hermes lacks this. Copy then mutate: [...arr].sort().",
        },
      ],
    },
  },
  {
    // Type-aware rules need the tsconfig, so they only cover the files it includes.
    files: ["src/**/*.ts", "src/**/*.tsx", "App.tsx", "index.ts"],
    plugins: expo.find((c) => c.plugins?.["@typescript-eslint"]).plugins,
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: __dirname },
    },
    rules: {
      "@typescript-eslint/no-unsafe-call": "warn",
      "@typescript-eslint/no-unsafe-member-access": "warn",
    },
  },
  {
    // Flat config scopes plugin names per object, so the @typescript-eslint
    // rules have to be reopened alongside the plugin Expo registers for them.
    files: ["**/*.ts", "**/*.tsx"],
    plugins: expo.find((c) => c.plugins?.["@typescript-eslint"]).plugins,
    rules: {
      // Both spellings are used deliberately across the codebase.
      "@typescript-eslint/array-type": "off",

      "@typescript-eslint/no-explicit-any": "error",

      // A leading underscore is the codebase's existing marker for a
      // deliberately unused binding (see services/off/auth.tsx).
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
    },
  },
  {
    // The contract test compares the online and offline service modules by
    // loading them with require() at test time, which is what the file is for.
    files: ["**/__tests__/**", "**/*.test.ts", "**/*.test.tsx"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  {
    // SheetJS documents and exports the namespace import. The named exports are
    // the same objects.
    files: ["src/utils/clientWorkoutParser.tsx"],
    rules: { "import/no-named-as-default-member": "off" },
  },
];
